namespace Godot;

// Godot's named colors (values from GodotSharp 4.5.1). Color(string) and Color.FromString
// fall back to this table for names that are not HTML hex codes.
public static class Colors
{
    public static Color AliceBlue => new(0xF0F8FFFFu);
    public static Color AntiqueWhite => new(0xFAEBD7FFu);
    public static Color Aqua => new(0x00FFFFFFu);
    public static Color Aquamarine => new(0x7FFFD4FFu);
    public static Color Azure => new(0xF0FFFFFFu);
    public static Color Beige => new(0xF5F5DCFFu);
    public static Color Bisque => new(0xFFE4C4FFu);
    public static Color Black => new(0x000000FFu);
    public static Color BlanchedAlmond => new(0xFFEBCDFFu);
    public static Color Blue => new(0x0000FFFFu);
    public static Color BlueViolet => new(0x8A2BE2FFu);
    public static Color Brown => new(0xA52A2AFFu);
    public static Color Burlywood => new(0xDEB887FFu);
    public static Color CadetBlue => new(0x5F9EA0FFu);
    public static Color Chartreuse => new(0x7FFF00FFu);
    public static Color Chocolate => new(0xD2691EFFu);
    public static Color Coral => new(0xFF7F50FFu);
    public static Color CornflowerBlue => new(0x6495EDFFu);
    public static Color Cornsilk => new(0xFFF8DCFFu);
    public static Color Crimson => new(0xDC143CFFu);
    public static Color Cyan => new(0x00FFFFFFu);
    public static Color DarkBlue => new(0x00008BFFu);
    public static Color DarkCyan => new(0x008B8BFFu);
    public static Color DarkGoldenrod => new(0xB8860BFFu);
    public static Color DarkGray => new(0xA9A9A9FFu);
    public static Color DarkGreen => new(0x006400FFu);
    public static Color DarkKhaki => new(0xBDB76BFFu);
    public static Color DarkMagenta => new(0x8B008BFFu);
    public static Color DarkOliveGreen => new(0x556B2FFFu);
    public static Color DarkOrange => new(0xFF8C00FFu);
    public static Color DarkOrchid => new(0x9932CCFFu);
    public static Color DarkRed => new(0x8B0000FFu);
    public static Color DarkSalmon => new(0xE9967AFFu);
    public static Color DarkSeaGreen => new(0x8FBC8FFFu);
    public static Color DarkSlateBlue => new(0x483D8BFFu);
    public static Color DarkSlateGray => new(0x2F4F4FFFu);
    public static Color DarkTurquoise => new(0x00CED1FFu);
    public static Color DarkViolet => new(0x9400D3FFu);
    public static Color DeepPink => new(0xFF1493FFu);
    public static Color DeepSkyBlue => new(0x00BFFFFFu);
    public static Color DimGray => new(0x696969FFu);
    public static Color DodgerBlue => new(0x1E90FFFFu);
    public static Color Firebrick => new(0xB22222FFu);
    public static Color FloralWhite => new(0xFFFAF0FFu);
    public static Color ForestGreen => new(0x228B22FFu);
    public static Color Fuchsia => new(0xFF00FFFFu);
    public static Color Gainsboro => new(0xDCDCDCFFu);
    public static Color GhostWhite => new(0xF8F8FFFFu);
    public static Color Gold => new(0xFFD700FFu);
    public static Color Goldenrod => new(0xDAA520FFu);
    public static Color Gray => new(0xBEBEBEFFu);
    public static Color Green => new(0x00FF00FFu);
    public static Color GreenYellow => new(0xADFF2FFFu);
    public static Color Honeydew => new(0xF0FFF0FFu);
    public static Color HotPink => new(0xFF69B4FFu);
    public static Color IndianRed => new(0xCD5C5CFFu);
    public static Color Indigo => new(0x4B0082FFu);
    public static Color Ivory => new(0xFFFFF0FFu);
    public static Color Khaki => new(0xF0E68CFFu);
    public static Color Lavender => new(0xE6E6FAFFu);
    public static Color LavenderBlush => new(0xFFF0F5FFu);
    public static Color LawnGreen => new(0x7CFC00FFu);
    public static Color LemonChiffon => new(0xFFFACDFFu);
    public static Color LightBlue => new(0xADD8E6FFu);
    public static Color LightCoral => new(0xF08080FFu);
    public static Color LightCyan => new(0xE0FFFFFFu);
    public static Color LightGoldenrod => new(0xFAFAD2FFu);
    public static Color LightGray => new(0xD3D3D3FFu);
    public static Color LightGreen => new(0x90EE90FFu);
    public static Color LightPink => new(0xFFB6C1FFu);
    public static Color LightSalmon => new(0xFFA07AFFu);
    public static Color LightSeaGreen => new(0x20B2AAFFu);
    public static Color LightSkyBlue => new(0x87CEFAFFu);
    public static Color LightSlateGray => new(0x778899FFu);
    public static Color LightSteelBlue => new(0xB0C4DEFFu);
    public static Color LightYellow => new(0xFFFFE0FFu);
    public static Color Lime => new(0x00FF00FFu);
    public static Color LimeGreen => new(0x32CD32FFu);
    public static Color Linen => new(0xFAF0E6FFu);
    public static Color Magenta => new(0xFF00FFFFu);
    public static Color Maroon => new(0xB03060FFu);
    public static Color MediumAquamarine => new(0x66CDAAFFu);
    public static Color MediumBlue => new(0x0000CDFFu);
    public static Color MediumOrchid => new(0xBA55D3FFu);
    public static Color MediumPurple => new(0x9370DBFFu);
    public static Color MediumSeaGreen => new(0x3CB371FFu);
    public static Color MediumSlateBlue => new(0x7B68EEFFu);
    public static Color MediumSpringGreen => new(0x00FA9AFFu);
    public static Color MediumTurquoise => new(0x48D1CCFFu);
    public static Color MediumVioletRed => new(0xC71585FFu);
    public static Color MidnightBlue => new(0x191970FFu);
    public static Color MintCream => new(0xF5FFFAFFu);
    public static Color MistyRose => new(0xFFE4E1FFu);
    public static Color Moccasin => new(0xFFE4B5FFu);
    public static Color NavajoWhite => new(0xFFDEADFFu);
    public static Color NavyBlue => new(0x000080FFu);
    public static Color OldLace => new(0xFDF5E6FFu);
    public static Color Olive => new(0x808000FFu);
    public static Color OliveDrab => new(0x6B8E23FFu);
    public static Color Orange => new(0xFFA500FFu);
    public static Color OrangeRed => new(0xFF4500FFu);
    public static Color Orchid => new(0xDA70D6FFu);
    public static Color PaleGoldenrod => new(0xEEE8AAFFu);
    public static Color PaleGreen => new(0x98FB98FFu);
    public static Color PaleTurquoise => new(0xAFEEEEFFu);
    public static Color PaleVioletRed => new(0xDB7093FFu);
    public static Color PapayaWhip => new(0xFFEFD5FFu);
    public static Color PeachPuff => new(0xFFDAB9FFu);
    public static Color Peru => new(0xCD853FFFu);
    public static Color Pink => new(0xFFC0CBFFu);
    public static Color Plum => new(0xDDA0DDFFu);
    public static Color PowderBlue => new(0xB0E0E6FFu);
    public static Color Purple => new(0xA020F0FFu);
    public static Color RebeccaPurple => new(0x663399FFu);
    public static Color Red => new(0xFF0000FFu);
    public static Color RosyBrown => new(0xBC8F8FFFu);
    public static Color RoyalBlue => new(0x4169E1FFu);
    public static Color SaddleBrown => new(0x8B4513FFu);
    public static Color Salmon => new(0xFA8072FFu);
    public static Color SandyBrown => new(0xF4A460FFu);
    public static Color SeaGreen => new(0x2E8B57FFu);
    public static Color Seashell => new(0xFFF5EEFFu);
    public static Color Sienna => new(0xA0522DFFu);
    public static Color Silver => new(0xC0C0C0FFu);
    public static Color SkyBlue => new(0x87CEEBFFu);
    public static Color SlateBlue => new(0x6A5ACDFFu);
    public static Color SlateGray => new(0x708090FFu);
    public static Color Snow => new(0xFFFAFAFFu);
    public static Color SpringGreen => new(0x00FF7FFFu);
    public static Color SteelBlue => new(0x4682B4FFu);
    public static Color Tan => new(0xD2B48CFFu);
    public static Color Teal => new(0x008080FFu);
    public static Color Thistle => new(0xD8BFD8FFu);
    public static Color Tomato => new(0xFF6347FFu);
    public static Color Transparent => new(0xFFFFFF00u);
    public static Color Turquoise => new(0x40E0D0FFu);
    public static Color Violet => new(0xEE82EEFFu);
    public static Color WebGray => new(0x808080FFu);
    public static Color WebGreen => new(0x008000FFu);
    public static Color WebMaroon => new(0x800000FFu);
    public static Color WebPurple => new(0x800080FFu);
    public static Color Wheat => new(0xF5DEB3FFu);
    public static Color White => new(0xFFFFFFFFu);
    public static Color WhiteSmoke => new(0xF5F5F5FFu);
    public static Color Yellow => new(0xFFFF00FFu);
    public static Color YellowGreen => new(0x9ACD32FFu);

    // Keys are upper-case with spaces, dashes, underscores, apostrophes and dots removed.
    internal static readonly System.Collections.Generic.Dictionary<string, Color> NamedColors = new()
    {
        ["ALICEBLUE"] = new(0xF0F8FFFFu),
        ["ANTIQUEWHITE"] = new(0xFAEBD7FFu),
        ["AQUA"] = new(0x00FFFFFFu),
        ["AQUAMARINE"] = new(0x7FFFD4FFu),
        ["AZURE"] = new(0xF0FFFFFFu),
        ["BEIGE"] = new(0xF5F5DCFFu),
        ["BISQUE"] = new(0xFFE4C4FFu),
        ["BLACK"] = new(0x000000FFu),
        ["BLANCHEDALMOND"] = new(0xFFEBCDFFu),
        ["BLUE"] = new(0x0000FFFFu),
        ["BLUEVIOLET"] = new(0x8A2BE2FFu),
        ["BROWN"] = new(0xA52A2AFFu),
        ["BURLYWOOD"] = new(0xDEB887FFu),
        ["CADETBLUE"] = new(0x5F9EA0FFu),
        ["CHARTREUSE"] = new(0x7FFF00FFu),
        ["CHOCOLATE"] = new(0xD2691EFFu),
        ["CORAL"] = new(0xFF7F50FFu),
        ["CORNFLOWERBLUE"] = new(0x6495EDFFu),
        ["CORNSILK"] = new(0xFFF8DCFFu),
        ["CRIMSON"] = new(0xDC143CFFu),
        ["CYAN"] = new(0x00FFFFFFu),
        ["DARKBLUE"] = new(0x00008BFFu),
        ["DARKCYAN"] = new(0x008B8BFFu),
        ["DARKGOLDENROD"] = new(0xB8860BFFu),
        ["DARKGRAY"] = new(0xA9A9A9FFu),
        ["DARKGREEN"] = new(0x006400FFu),
        ["DARKKHAKI"] = new(0xBDB76BFFu),
        ["DARKMAGENTA"] = new(0x8B008BFFu),
        ["DARKOLIVEGREEN"] = new(0x556B2FFFu),
        ["DARKORANGE"] = new(0xFF8C00FFu),
        ["DARKORCHID"] = new(0x9932CCFFu),
        ["DARKRED"] = new(0x8B0000FFu),
        ["DARKSALMON"] = new(0xE9967AFFu),
        ["DARKSEAGREEN"] = new(0x8FBC8FFFu),
        ["DARKSLATEBLUE"] = new(0x483D8BFFu),
        ["DARKSLATEGRAY"] = new(0x2F4F4FFFu),
        ["DARKTURQUOISE"] = new(0x00CED1FFu),
        ["DARKVIOLET"] = new(0x9400D3FFu),
        ["DEEPPINK"] = new(0xFF1493FFu),
        ["DEEPSKYBLUE"] = new(0x00BFFFFFu),
        ["DIMGRAY"] = new(0x696969FFu),
        ["DODGERBLUE"] = new(0x1E90FFFFu),
        ["FIREBRICK"] = new(0xB22222FFu),
        ["FLORALWHITE"] = new(0xFFFAF0FFu),
        ["FORESTGREEN"] = new(0x228B22FFu),
        ["FUCHSIA"] = new(0xFF00FFFFu),
        ["GAINSBORO"] = new(0xDCDCDCFFu),
        ["GHOSTWHITE"] = new(0xF8F8FFFFu),
        ["GOLD"] = new(0xFFD700FFu),
        ["GOLDENROD"] = new(0xDAA520FFu),
        ["GRAY"] = new(0xBEBEBEFFu),
        ["GREEN"] = new(0x00FF00FFu),
        ["GREENYELLOW"] = new(0xADFF2FFFu),
        ["HONEYDEW"] = new(0xF0FFF0FFu),
        ["HOTPINK"] = new(0xFF69B4FFu),
        ["INDIANRED"] = new(0xCD5C5CFFu),
        ["INDIGO"] = new(0x4B0082FFu),
        ["IVORY"] = new(0xFFFFF0FFu),
        ["KHAKI"] = new(0xF0E68CFFu),
        ["LAVENDER"] = new(0xE6E6FAFFu),
        ["LAVENDERBLUSH"] = new(0xFFF0F5FFu),
        ["LAWNGREEN"] = new(0x7CFC00FFu),
        ["LEMONCHIFFON"] = new(0xFFFACDFFu),
        ["LIGHTBLUE"] = new(0xADD8E6FFu),
        ["LIGHTCORAL"] = new(0xF08080FFu),
        ["LIGHTCYAN"] = new(0xE0FFFFFFu),
        ["LIGHTGOLDENROD"] = new(0xFAFAD2FFu),
        ["LIGHTGRAY"] = new(0xD3D3D3FFu),
        ["LIGHTGREEN"] = new(0x90EE90FFu),
        ["LIGHTPINK"] = new(0xFFB6C1FFu),
        ["LIGHTSALMON"] = new(0xFFA07AFFu),
        ["LIGHTSEAGREEN"] = new(0x20B2AAFFu),
        ["LIGHTSKYBLUE"] = new(0x87CEFAFFu),
        ["LIGHTSLATEGRAY"] = new(0x778899FFu),
        ["LIGHTSTEELBLUE"] = new(0xB0C4DEFFu),
        ["LIGHTYELLOW"] = new(0xFFFFE0FFu),
        ["LIME"] = new(0x00FF00FFu),
        ["LIMEGREEN"] = new(0x32CD32FFu),
        ["LINEN"] = new(0xFAF0E6FFu),
        ["MAGENTA"] = new(0xFF00FFFFu),
        ["MAROON"] = new(0xB03060FFu),
        ["MEDIUMAQUAMARINE"] = new(0x66CDAAFFu),
        ["MEDIUMBLUE"] = new(0x0000CDFFu),
        ["MEDIUMORCHID"] = new(0xBA55D3FFu),
        ["MEDIUMPURPLE"] = new(0x9370DBFFu),
        ["MEDIUMSEAGREEN"] = new(0x3CB371FFu),
        ["MEDIUMSLATEBLUE"] = new(0x7B68EEFFu),
        ["MEDIUMSPRINGGREEN"] = new(0x00FA9AFFu),
        ["MEDIUMTURQUOISE"] = new(0x48D1CCFFu),
        ["MEDIUMVIOLETRED"] = new(0xC71585FFu),
        ["MIDNIGHTBLUE"] = new(0x191970FFu),
        ["MINTCREAM"] = new(0xF5FFFAFFu),
        ["MISTYROSE"] = new(0xFFE4E1FFu),
        ["MOCCASIN"] = new(0xFFE4B5FFu),
        ["NAVAJOWHITE"] = new(0xFFDEADFFu),
        ["NAVYBLUE"] = new(0x000080FFu),
        ["OLDLACE"] = new(0xFDF5E6FFu),
        ["OLIVE"] = new(0x808000FFu),
        ["OLIVEDRAB"] = new(0x6B8E23FFu),
        ["ORANGE"] = new(0xFFA500FFu),
        ["ORANGERED"] = new(0xFF4500FFu),
        ["ORCHID"] = new(0xDA70D6FFu),
        ["PALEGOLDENROD"] = new(0xEEE8AAFFu),
        ["PALEGREEN"] = new(0x98FB98FFu),
        ["PALETURQUOISE"] = new(0xAFEEEEFFu),
        ["PALEVIOLETRED"] = new(0xDB7093FFu),
        ["PAPAYAWHIP"] = new(0xFFEFD5FFu),
        ["PEACHPUFF"] = new(0xFFDAB9FFu),
        ["PERU"] = new(0xCD853FFFu),
        ["PINK"] = new(0xFFC0CBFFu),
        ["PLUM"] = new(0xDDA0DDFFu),
        ["POWDERBLUE"] = new(0xB0E0E6FFu),
        ["PURPLE"] = new(0xA020F0FFu),
        ["REBECCAPURPLE"] = new(0x663399FFu),
        ["RED"] = new(0xFF0000FFu),
        ["ROSYBROWN"] = new(0xBC8F8FFFu),
        ["ROYALBLUE"] = new(0x4169E1FFu),
        ["SADDLEBROWN"] = new(0x8B4513FFu),
        ["SALMON"] = new(0xFA8072FFu),
        ["SANDYBROWN"] = new(0xF4A460FFu),
        ["SEAGREEN"] = new(0x2E8B57FFu),
        ["SEASHELL"] = new(0xFFF5EEFFu),
        ["SIENNA"] = new(0xA0522DFFu),
        ["SILVER"] = new(0xC0C0C0FFu),
        ["SKYBLUE"] = new(0x87CEEBFFu),
        ["SLATEBLUE"] = new(0x6A5ACDFFu),
        ["SLATEGRAY"] = new(0x708090FFu),
        ["SNOW"] = new(0xFFFAFAFFu),
        ["SPRINGGREEN"] = new(0x00FF7FFFu),
        ["STEELBLUE"] = new(0x4682B4FFu),
        ["TAN"] = new(0xD2B48CFFu),
        ["TEAL"] = new(0x008080FFu),
        ["THISTLE"] = new(0xD8BFD8FFu),
        ["TOMATO"] = new(0xFF6347FFu),
        ["TRANSPARENT"] = new(0xFFFFFF00u),
        ["TURQUOISE"] = new(0x40E0D0FFu),
        ["VIOLET"] = new(0xEE82EEFFu),
        ["WEBGRAY"] = new(0x808080FFu),
        ["WEBGREEN"] = new(0x008000FFu),
        ["WEBMAROON"] = new(0x800000FFu),
        ["WEBPURPLE"] = new(0x800080FFu),
        ["WHEAT"] = new(0xF5DEB3FFu),
        ["WHITE"] = new(0xFFFFFFFFu),
        ["WHITESMOKE"] = new(0xF5F5F5FFu),
        ["YELLOW"] = new(0xFFFF00FFu),
        ["YELLOWGREEN"] = new(0x9ACD32FFu),
    };
}
